### ISSUE TITLE
unknown CMake command: generate_module_info

### ISSUE THREAD

**Issue by anne-gropler** [cginternals/openll#12]
I am trying to setup the examples of this project with CMake.

The function `generate_module_info` is used in source/examles/CMakeLists.txt, but CMake does not know it.
Am I missing some cmake-dependency?

**Comment by anne-gropler** [comment]
Same for `export_module_info` and `install_module_info`.

**Comment by sbusch42** [comment]
Those commands were part of a very old version of cpplocate, long deprecated. Also, the cpp-implementation of openll in this repository is very old and has since been superseded by cginternals/openll-cpp. I've been told this old implementation had been removed, but obviously it has not.

If you really need to get this old version going, you will need to adjust and update it to the newer codebase. I would suggest just removing the old cpplocate stuff and referencing data using absolute paths for the beginning. Also, there might have been some changes in glbinding and globjects, which will need to be updated.

**Comment by anne-gropler** [comment]
Thanks for your quick answer!
I wanted to setup and try out the labeling examples, so it's not that I absolutely need this to run. This old implementation is not removed because of these examples. Some parts of them (e.g., point-based layouting) will be integrated soon-ish in other places, so please don't remove them for now.

**Comment by scheibel** [comment]
Porting the examples to the openll-cpp dependency and a current cmake-init setup is still time-consuming (I started this but aborted it soon after without committing). I'm not sure if your approach will work out.
